### PR TITLE
API for using external buffer

### PR DESCRIPTION
**Pull request by augustoroman**

### CODE REVIEW

**Comment by karalabe** [comment]
No cheating :P 

We are all aware that using a decent size default buffer can make small ops significantly faster, but if I particularly ask for a small buffer size, it may be inadvisable to ignore that (maybe not, debatable). Additionally for the sake of fair comparison, let's all use non-"cheating" implementations. If the proposal is accepted, we can debate these "intelligent" choices, but until then, let's keep to the same rules :)

**Comment by augustoroman** [comment]
Fair enough -- removed the cheating commit.  ;-)  I still think that the Pipe-based API should take an externally-provided buffer, though.  I intend to refactor my code to conform to the full Pipe solution, but using the signature:

  func Pipe(buf []byte) (*Reader, *Writer)

As per the commit msg:  It allows the caller to reuse buffers (e.g. arena-allocated bufs), but doesn't inconvenience casual users who can simply do "make([]byte, N)" inline.

**Comment by karalabe** [comment]
The reusable buffer is not a bad idea actually, maybe we can discuss it on the mailing list more openly.

**Comment by karalabe** [comment]
PS: Just occurred to me, that one of the problems of these intelligent choices is that they make it very hard to properly test and validate the solution. Jan's solution particularly takes advantage of a lot of things, and it took me many times a lot of effort to tune the shootout to indeed catch these faults (I've spent 1h+ today to create a repro, make the charts, etc). This is one more reason why I would like the implementation to honor the user's choice, because then there's no magic, you _know_ what will happen.

**Pull request merged**
